name: Deploy to Firebase

# Run this workflow every time a new commit pushed to your repository
on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: install firebase
      run: npm i firebase-tools -g  
    - name: deploy
      run: firebase deploy --token 1//06alc8OZXirv5CgYIARAAGAYSNwF-L9IrDBxO5iO2rPPMF_9TqOGWK_MN-_49oObZ6Wojd335V12kesSd2_S_8dC14lcvSkeZTZ4